version: '3'
services:
 frontend:
  build:
   context: ./frontend
  ports:
   - "80:80"
  networks:
   - app-network
 backend:
  build:
   context: ./backend
  ports:
   - "3030:3030"
  networks:
   - app-network
networks:
 app-network:
